from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Solar_terms', src, depend = ['SOLAR_TERMS_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
